In [2]:
import numpy as np

#### Creating arrays in Numpy

In [3]:
myArray = np.array([1, 2, 3])
print(myArray)

[1 2 3]


In [7]:
# Creating a zero-dimension array (also called scalers)

zero_dim = np.array(34)
print(zero_dim)
print(zero_dim.ndim)

34
0


In [9]:
# Creating a one-dimension array

one_dim = np.array([1, 3, 5])
print(one_dim)
print(one_dim.ndim)

[1 3 5]
1


In [11]:
# Creating a two-dimension array

two_dim = np.array([[1, 3, 5],[2, 4, 6]])
print(two_dim)
print(two_dim.ndim)

[[1 3 5]
 [2 4 6]]
2


In [14]:
# Creating a three-dimension array

three_dim = np.array([[[1, 3, 5],[2, 4, 6]], [[4, 5, 6],[7, 8, 9]]])
print(three_dim)
print(three_dim.ndim)

[[[1 3 5]
  [2 4 6]]

 [[4 5 6]
  [7 8 9]]]
3


#### Indexing Numpy Arrays

In [16]:
myArray = np.array([10, 20, 30, 40, 50])
myArray[1] #Accessing the second element in the array

20

In [17]:
myArray[0] #Accessing the first element in the array

10

In [22]:
twoDim = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
twoDim[1, 3]

9

#### Slicing Numpy Arrays

In [26]:
myArray = np.array([10, 20, 30, 40, 50])
myArray[0:4]

array([10, 20, 30, 40])

In [29]:
twoDim = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
twoDim[1, 0:4]

array([6, 7, 8, 9])

#### Copying an Array

In [30]:
originalArray = np.array([1, 2, 3, 4, 5])

copiedArray = originalArray.copy()

#### Viewing Arrays

In [31]:
originalArray = np.array([1, 2, 3, 4, 5])

arrayView = originalArray.view()

#### Shape of an Array

In [35]:
myArray = np.array([10, 20, 30, 40, 50])
print(myArray.shape)

(5,)


In [38]:
twoDim = np.array([[1, 2, 3, 4], [6, 7, 8, 9], [12, 13, 14, 15]])
print(twoDim.shape)

(3, 4)


#### Reshaping an Array

In [40]:
# Reshaping from 1d to 2d 

# the outermost dimension will have 2 arrays; 
# and those arrays will have 5 elements

arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

newArray = arr.reshape(2, 5)
print(newArray)

[[ 10  20  30  40  50]
 [ 60  70  80  90 100]]


In [41]:
# Reshaping from 1d to 3d 

# the outermost array would have 2 arrays that would hold 3 arrays
# those 3 arrays would have 2 elements

arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120])

newArray = arr.reshape(2, 3, 2)

print(newArray)

[[[ 10  20]
  [ 30  40]
  [ 50  60]]

 [[ 70  80]
  [ 90 100]
  [110 120]]]


#### Basic Operation in Numpy

In [45]:
# arange function

# myArray = np.arange(start, stop, step)

myArray = np.arange(0, 10, 2)

print(myArray)

[0 2 4 6 8]


In [47]:
secondArray = np.arange(101, 105, 1)
print(secondArray)

[101 102 103 104]


In [48]:
# Basic Mathematical Operations


# Addition

a = np.array([10, 20, 30, 40])
b = np.array([5, 10, 15, 20])

print(a + b)

[15 30 45 60]


In [49]:
# Subtraction
print(a - b)

[ 5 10 15 20]


In [50]:
# Multiplication
print(a * b)

[ 50 200 450 800]


In [51]:
# Division
print(a / b)

[2. 2. 2. 2.]


In [53]:
# Multiply all the elements in an array by a number
print(a)
print(a * 2)

[10 20 30 40]
[20 40 60 80]


In [54]:
print(a ** 2)

[ 100  400  900 1600]


In [55]:
# sqrt
print(np.sqrt(a))

[3.16227766 4.47213595 5.47722558 6.32455532]


#### Data Analytics Operations in Numpy

In [57]:
# Create our arrays

one_dim = np.array([10, 20, 30, 40])
two_dim = np.array([[4, 8, 12, 16], [2, 4, 6, 8]])

In [58]:
# Summations

# 1d
print(sum(one_dim))

100


In [59]:
# 2d
print(sum(two_dim))

[ 6 12 18 24]


In [60]:
print(one_dim.sum())

100


In [61]:
print(two_dim.sum())

60


In [63]:
# Min and Max

#Min
print(one_dim.min())
print(two_dim.min())

10
2


In [64]:
#Max
print(one_dim.max())
print(two_dim.max())

40
16


In [65]:
arr = np.array([[4, 8, 12, 16], [2, 4, 6, 8], [5, 10, 15, 20]])
print(arr)

[[ 4  8 12 16]
 [ 2  4  6  8]
 [ 5 10 15 20]]


In [66]:
# summation across rows in arrays
print(arr.sum(axis=1))

[40 20 50]


In [73]:
# summation across columns in arrays
print(arr.sum(axis=0))

[11 22 33 44]


In [77]:
print(arr)

[[ 4  8 12 16]
 [ 2  4  6  8]
 [ 5 10 15 20]]


In [78]:
# mean across the rows
print(arr.mean(axis = 1))

[10.   5.  12.5]


In [79]:
# mean across the columns
print(arr.mean(axis = 0))

[ 3.66666667  7.33333333 11.         14.66666667]


In [81]:
o = np.arange(0, 101, 2)

In [82]:
o.shape

(51,)