In [7]:
# import libraries

import numpy as np


# let us prompt the user for input

n_rows = int(input('Enter desired number of rows: '))
n_columns = int(input('Enter desired number of columns: '))
min_value = int(input('Enter desired minimum value: '))
max_value = int(input('Enter desired maximum value: '))

Enter desired number of rows: 10
Enter desired number of columns: 10
Enter desired minimum value: 1
Enter desired maximum value: 100


In [8]:
# generating a numpy array with random value within the user-specified range

randomArray = np.random.randint(min_value, max_value + 1, size = (n_rows, n_columns))

In [9]:
# printing the generated array

print(randomArray)

[[ 56  15  82  53  57  13  85  71  75  81]
 [ 16  93  96  67  83  31  21  68  50   8]
 [ 17  87  92  95  95  26  74  59  14  79]
 [ 50  25   8  95  83  47  99  22  80  79]
 [ 76   2  58  80  96  47  72  54  57  12]
 [ 44  19  14  94  59  80  67  81  47  75]
 [ 96   7  41  30   4  97   7  40  83  90]
 [ 88  79  69  60 100  72   4  40  10   2]
 [  8  44  99  18  32  16  24  62  34  47]
 [ 21  77   8  37  19  15  53  51  26   5]]
